In [2]:
import pandas as pd
print(pd.__version__)

3.0.2

In [4]:
marks=pd.Series([20,30,11,76,88])
print(marks)

0    20
1    30
2    11
3    76
4    88
dtype: int64

In [6]:
df=pd.read_csv("marks1.csv")
print(df)

  Student\tEnglish\tMathematics\tScience\tSocial Science\tComputer
0                      Student 1\t78\t85\t82\t74\t90
1                      Student 2\t65\t72\t70\t68\t75
2                      Student 3\t91\t95\t89\t92\t96
3                      Student 4\t56\t61\t58\t60\t64
4                      Student 5\t84\t79\t88\t81\t86
5                      Student 6\t73\t69\t75\t71\t77
6                      Student 7\t88\t90\t92\t85\t94
7                      Student 8\t62\t58\t64\t66\t60
8                      Student 9\t80\t83\t78\t82\t85
9                     Student 10\t95\t97\t94\t96\t98

In [10]:
marks=pd.Series([30,40,50],index=["A","B","C"])
print(marks)

A    30
B    40
C    50
dtype: int64

In [5]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df)

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90

In [25]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df[["Name","English"]]) 
print(df.loc[0]) 
print(df.iloc[1])

           Name  English
0  Aarav Sharma       85
1   Priya Verma       90
2   Rahul Singh       76
3  Ananya Gupta       95
4  Vikram Yadav       68
5   Neha Mishra       88
6  Aditya Kumar       79
7   Sneha Patel       92
8   Rohan Mehta       73
9   Kavya Joshi       86
Name              Aarav Sharma
English                     85
Mathematics                 92
Science                     78
Social Studies              88
Computer                    95
Name: 0, dtype: object
Name              Priya Verma
English                    90
Mathematics                87
Science                    91
Social Studies             85
Computer                   89
Name: 1, dtype: object

In [6]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df.isnull())
print(df.fillna(0))

    Name  English  Mathematics  Science  Social Studies  Computer
0  False    False        False    False           False     False
1  False    False        False    False           False     False
2  False    False        False    False           False     False
3  False    False        False    False           False     False
4  False    False        False    False           False     False
5  False    False        False    False           False     False
6  False    False        False    False           False     False
7  False    False        False    False           False     False
8  False    False        False    False           False     False
9  False    False        False    False           False     False
           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90

In [26]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df[["Name","English"]]) 
print(df.loc[0]) 
print(df.iloc[1])
print(df.head())
print(df.tail())

           Name  English
0  Aarav Sharma       85
1   Priya Verma       90
2   Rahul Singh       76
3  Ananya Gupta       95
4  Vikram Yadav       68
5   Neha Mishra       88
6  Aditya Kumar       79
7   Sneha Patel       92
8   Rohan Mehta       73
9   Kavya Joshi       86
Name              Aarav Sharma
English                     85
Mathematics                 92
Science                     78
Social Studies              88
Computer                    95
Name: 0, dtype: object
Name              Priya Verma
English                    90
Mathematics                87
Science                    91
Social Studies             85
Computer                   89
Name: 1, dtype: object
           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
           Name  English  Mathematics  Science  Social Studies  Computer
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90

In [7]:
df.shape

(10, 6)

In [10]:
print(df.columns)

Index(['Name', 'English', 'Mathematics', 'Science', 'Social Studies',
       'Computer'],
      dtype='str')

In [11]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [12]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            10 non-null     str
 1   English         10 non-null     int64
 2   Mathematics     10 non-null     int64
 3   Science         10 non-null     int64
 4   Social Studies  10 non-null     int64
 5   Computer        10 non-null     int64
dtypes: int64(5), str(1)
memory usage: 512.0 bytes
None

In [13]:
import pandas as pd
df=pd.read_csv("data_100_rows_20_columns.csv")
print(df)

    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0         48        45        78        24         8        85         1
1         26        97        53        49        26         5        72
2         63        48        77        51        40        95        61
3          2        48        33        75        60        44        59
4         84        54       100        67        37        34        73
..       ...       ...       ...       ...       ...       ...       ...
95        62        53        81        90        38        65        67
96         5        94        23        33        19        60        24
97        15        40        84        10         9        47        27
98        25        73         9        16         4        33        55
99        36        79        49        14        22        12        27

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0         58        54         50         64         49         95         75
1         12        54         86         98         44         82         26
2        100        29         20         83         19         34         46
3         59        87         69         80         34         75         61
4         23        16         51         69         35          7         41
..       ...       ...        ...        ...        ...        ...        ...
95        62        54         54         32         17         91         63
96        73        58          5         36         17         83         78
97        15        96          7          3         37         96         64
98         3        20         88         37         74         49         13
99        57        92          6         51         88         28         32

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0          80         48         91          3         22         77
1          61         61         95         58         83         85
2          58         43         34          7         15         78
3          15         17         12         77          1         27
4          89         55         48         64         57         28
..        ...        ...        ...        ...        ...        ...
95        100         88         24          8         58         62
96         24         65         25         27         41         54
97         26         62         92         31          7         30
98         57         43         23         79         64         56
99         25         27         32         29         95         81

[100 rows x 20 columns]

In [4]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.info())
print(df.head()) 
print(df.tail()) 
print(df.isnull())

(20, 1)
Index(['Employee ID\t      Name\t     Department\t          Salary'], dtype='str')
RangeIndex(start=0, stop=20, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 1 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Employee ID	      Name	     Department	          Salary  20 non-null     str
dtypes: str(1)
memory usage: 152.0 bytes
None
  Employee ID\t      Name\t     Department\t          Salary
0  EMP001\t              Aarav Sharma\tHR\t      ...
1  EMP002\t               Priya Singh\tFinance   ...
2  EMP003\t               Rahul Verma\tIT\t      ...
3  EMP004\t               Sneha Gupta\tMarketing\...
4  EMP005\t               Arjun Mehta\tSales\t   ...
   Employee ID\t      Name\t     Department\t          Salary
15  EMP016\t               Kavya Iyer\tIT\t       ...
16  EMP017\t               Nitin Chawla\tSales\t  ...
17  EMP018\t               Riya Bansal\tMarketing\...
18  EMP019\t               Manish Kumar\tOperation...
19  EMP020\t               Simran Kaur\tFinance   ...
    Employee ID\t      Name\t     Department\t          Salary
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
5                                               False
6                                               False
7                                               False
8                                               False
9                                               False
10                                              False
11                                              False
12                                              False
13                                              False
14                                              False
15                                              False
16                                              False
17                                              False
18                                              False
19                                              False

In [16]:
import pandas as pd
df=pd.read_csv("employes.csv")
print(df)

   Employee ID\t      Name\t     Department\t          Salary
0   EMP001\t              Aarav Sharma\tHR\t      ...
1   EMP002\t               Priya Singh\tFinance   ...
2   EMP003\t               Rahul Verma\tIT\t      ...
3   EMP004\t               Sneha Gupta\tMarketing\...
4   EMP005\t               Arjun Mehta\tSales\t   ...
5   EMP006\t               Neha Kapoor\tIT\t      ...
6   EMP007\t               Karan Malhotra\tFinance...
7   EMP008\t               Ananya Joshi\tHR\t     ...
8   EMP009\t               Vivek Patel\tOperations...
9   EMP010\t               Isha Nair\tMarketing\t ...
10  EMP011\t               Rohan Das\tIT\t        ...
11  EMP012\t               Meera Reddy\tSales\t   ...
12  EMP013\t               Aditya Yadav\tOperation...
13  EMP014\t               Pooja Mishra\tHR\t     ...
14  EMP015\t               Saurabh Jain\tFinance\t...
15  EMP016\t               Kavya Iyer\tIT\t       ...
16  EMP017\t               Nitin Chawla\tSales\t  ...
17  EMP018\t               Riya Bansal\tMarketing\...
18  EMP019\t               Manish Kumar\tOperation...
19  EMP020\t               Simran Kaur\tFinance   ...

In [3]:
import pandas as pd
df=pd.read_csv("employes2.csv")
print(df.isnull())
print(df.fillna(0))

    Employee ID\t      Name\t     Department\t          Salary
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
5                                               False
6                                               False
7                                               False
8                                               False
9                                               False
10                                              False
11                                              False
12                                              False
13                                              False
14                                              False
15                                              False
16                                              False
17                                              False
18                                              False
19                                              False
   Employee ID\t      Name\t     Department\t          Salary
0   EMP001\t              Aarav Sharma\tHR\t      ...
1   EMP002\t               Priya Singh\tFinance   ...
2   EMP003\t               Rahul Verma\tIT\t      ...
3   EMP004\t               Sneha Gupta\tMarketing\...
4   EMP005\t               Arjun Mehta\tSales\t   ...
5   EMP006\t               Neha Kapoor\tIT\t      ...
6   EMP007\t               Karan Malhotra\tFinance...
7   EMP008\t               Ananya Joshi\tHR\t     ...
8   EMP009\t               Vivek Patel\tOperations...
9   EMP010\t               Isha Nair\tMarketing\t ...
10    EMP011\t               Rohan Das\tIT\t
11  EMP012\t               Meera Reddy\tSales\t   ...
12  EMP013\t               Aditya Yadav\tOperation...
13  EMP014\t               Pooja Mishra\tHR\t     ...
14  EMP015\t               Saurabh Jain\tFinance\t...
15  EMP016\t               Kavya Iyer\tIT\t       ...
16  EMP017\t               Nitin Chawla\tSales\t  ...
17  EMP018\t               Riya Bansal\tMarketing\...
18  EMP019\t               Manish Kumar\tOperation...
19  EMP020\t               Simran Kaur\tFinance   ...

In [12]:
print(df["bonus"]==5000)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: bonus, dtype: bool

In [1]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df)

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90

In [2]:
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.index) 
print(df.info())
print(df.describe())

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
           Name  English  Mathematics  Science  Social Studies  Computer
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90
(10, 6)
Index(['Name', 'English', 'Mathematics', 'Science', 'Social Studies',
       'Computer'],
      dtype='str')
RangeIndex(start=0, stop=10, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            10 non-null     str
 1   English         10 non-null     int64
 2   Mathematics     10 non-null     int64
 3   Science         10 non-null     int64
 4   Social Studies  10 non-null     int64
 5   Computer        10 non-null     int64
dtypes: int64(5), str(1)
memory usage: 512.0 bytes
None
         English  Mathematics    Science  Social Studies   Computer
count  10.000000     10.00000  10.000000       10.000000  10.000000
mean   83.200000     85.60000  84.700000       83.700000  86.900000
std     8.829244      6.07728   8.340663        7.394442   7.430418
min    68.000000     75.00000  72.000000       70.000000  76.000000
25%    76.750000     81.75000  78.500000       79.250000  82.250000
50%    85.500000     86.50000  86.500000       86.000000  87.500000
75%    89.500000     90.50000  90.500000       89.500000  92.250000
max    95.000000     93.00000  96.000000       92.000000  98.000000

In [3]:
import pandas as pd
df=pd.read_csv("employee5.csv")
df.fillna("not available")

    ID           Name Department         Salary
0    1          Aarav         HR        45000.0
1    2          Priya         IT        55000.0
2    3          Rahul    Finance        60000.0
3    4         Ananya  Marketing        50000.0
4    5         Vikram      Sales  not available
5    6           Neha         IT        65000.0
6    7          Rohan         HR        48000.0
7    8          Sneha    Finance        70000.0
8    9           Amit  Marketing  not available
9   10          Pooja      Sales        58000.0
10  11          Karan         IT        62000.0
11  12           Isha         HR        47000.0
12  13          Arjun    Finance        75000.0
13  14          Meera  Marketing        51000.0
14  15  not available      Sales        59000.0
15  16          Kavya         IT        68000.0
16  17         Suresh         HR        49000.0
17  18           Riya    Finance        72000.0
18  19         Manish  Marketing  not available
19  20          Tanya      Sales        56000.0

In [4]:
import pandas as pd
df=pd.read_csv("employee5.csv")
print(df.isnull())
print(df.isnull().sum())
df.fillna(5)
df.fillna(0)
df.fillna("not available")

       ID   Name  Department  Salary
0   False  False       False   False
1   False  False       False   False
2   False  False       False   False
3   False  False       False   False
4   False  False       False    True
5   False  False       False   False
6   False  False       False   False
7   False  False       False   False
8   False  False       False    True
9   False  False       False   False
10  False  False       False   False
11  False  False       False   False
12  False  False       False   False
13  False  False       False   False
14  False   True       False   False
15  False  False       False   False
16  False  False       False   False
17  False  False       False   False
18  False  False       False    True
19  False  False       False   False
ID            0
Name          1
Department    0
Salary        3
dtype: int64

    ID           Name Department         Salary
0    1          Aarav         HR        45000.0
1    2          Priya         IT        55000.0
2    3          Rahul    Finance        60000.0
3    4         Ananya  Marketing        50000.0
4    5         Vikram      Sales  not available
5    6           Neha         IT        65000.0
6    7          Rohan         HR        48000.0
7    8          Sneha    Finance        70000.0
8    9           Amit  Marketing  not available
9   10          Pooja      Sales        58000.0
10  11          Karan         IT        62000.0
11  12           Isha         HR        47000.0
12  13          Arjun    Finance        75000.0
13  14          Meera  Marketing        51000.0
14  15  not available      Sales        59000.0
15  16          Kavya         IT        68000.0
16  17         Suresh         HR        49000.0
17  18           Riya    Finance        72000.0
18  19         Manish  Marketing  not available
19  20          Tanya      Sales        56000.0

In [5]:
df.groupby("Department")["Salary"].mean()

Department
Finance      69250.000000
HR           47250.000000
IT           62500.000000
Marketing    50500.000000
Sales        57666.666667
Name: Salary, dtype: float64

In [6]:
print(df.isnull())

       ID   Name  Department  Salary
0   False  False       False   False
1   False  False       False   False
2   False  False       False   False
3   False  False       False   False
4   False  False       False    True
5   False  False       False   False
6   False  False       False   False
7   False  False       False   False
8   False  False       False    True
9   False  False       False   False
10  False  False       False   False
11  False  False       False   False
12  False  False       False   False
13  False  False       False   False
14  False   True       False   False
15  False  False       False   False
16  False  False       False   False
17  False  False       False   False
18  False  False       False    True
19  False  False       False   False

In [7]:
print(df.isnull().sum())

ID            0
Name          1
Department    0
Salary        3
dtype: int64

In [8]:
df.dropna()

    ID    Name Department   Salary
0    1   Aarav         HR  45000.0
1    2   Priya         IT  55000.0
2    3   Rahul    Finance  60000.0
3    4  Ananya  Marketing  50000.0
5    6    Neha         IT  65000.0
6    7   Rohan         HR  48000.0
7    8   Sneha    Finance  70000.0
9   10   Pooja      Sales  58000.0
10  11   Karan         IT  62000.0
11  12    Isha         HR  47000.0
12  13   Arjun    Finance  75000.0
13  14   Meera  Marketing  51000.0
15  16   Kavya         IT  68000.0
16  17  Suresh         HR  49000.0
17  18    Riya    Finance  72000.0
19  20   Tanya      Sales  56000.0

In [9]:
df.duplicated()
df.drop_duplicates()

    ID    Name Department   Salary
0    1   Aarav         HR  45000.0
1    2   Priya         IT  55000.0
2    3   Rahul    Finance  60000.0
3    4  Ananya  Marketing  50000.0
4    5  Vikram      Sales      NaN
5    6    Neha         IT  65000.0
6    7   Rohan         HR  48000.0
7    8   Sneha    Finance  70000.0
8    9    Amit  Marketing      NaN
9   10   Pooja      Sales  58000.0
10  11   Karan         IT  62000.0
11  12    Isha         HR  47000.0
12  13   Arjun    Finance  75000.0
13  14   Meera  Marketing  51000.0
14  15     NaN      Sales  59000.0
15  16   Kavya         IT  68000.0
16  17  Suresh         HR  49000.0
17  18    Riya    Finance  72000.0
18  19  Manish  Marketing      NaN
19  20   Tanya      Sales  56000.0

In [10]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [11]:
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
print(df)

    ID    Name Department        Salary
0    1   Aarav         HR  45000.000000
1    2   Priya         IT  55000.000000
2    3   Rahul    Finance  60000.000000
3    4  Ananya  Marketing  50000.000000
4    5  Vikram      Sales  58235.294118
5    6    Neha         IT  65000.000000
6    7   Rohan         HR  48000.000000
7    8   Sneha    Finance  70000.000000
8    9    Amit  Marketing  58235.294118
9   10   Pooja      Sales  58000.000000
10  11   Karan         IT  62000.000000
11  12    Isha         HR  47000.000000
12  13   Arjun    Finance  75000.000000
13  14   Meera  Marketing  51000.000000
14  15     NaN      Sales  59000.000000
15  16   Kavya         IT  68000.000000
16  17  Suresh         HR  49000.000000
17  18    Riya    Finance  72000.000000
18  19  Manish  Marketing  58235.294118
19  20   Tanya      Sales  56000.000000

In [12]:
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
print(df)

    ID    Name Department        Salary
0    1   Aarav         HR  45000.000000
1    2   Priya         IT  55000.000000
2    3   Rahul    Finance  60000.000000
3    4  Ananya  Marketing  50000.000000
4    5  Vikram      Sales  58235.294118
5    6    Neha         IT  65000.000000
6    7   Rohan         HR  48000.000000
7    8   Sneha    Finance  70000.000000
8    9    Amit  Marketing  58235.294118
9   10   Pooja      Sales  58000.000000
10  11   Karan         IT  62000.000000
11  12    Isha         HR  47000.000000
12  13   Arjun    Finance  75000.000000
13  14   Meera  Marketing  51000.000000
14  15     NaN      Sales  59000.000000
15  16   Kavya         IT  68000.000000
16  17  Suresh         HR  49000.000000
17  18    Riya    Finance  72000.000000
18  19  Manish  Marketing  58235.294118
19  20   Tanya      Sales  56000.000000

In [13]:
import pandas as pd
df=pd.read_csv("people1.csv")
print(df.isnull())
print(df.fillna(0))

        ID   Name    Age  Gender   City  Occupation  Salary
0    False  False  False   False  False       False   False
1    False  False   True   False  False        True   False
2    False  False  False   False  False       False   False
3    False   True  False   False   True       False   False
4    False  False  False   False  False       False   False
..     ...    ...    ...     ...    ...         ...     ...
995  False  False  False   False  False       False   False
996  False  False  False   False  False       False   False
997  False  False  False   False  False       False   False
998  False  False  False    True  False       False   False
999  False  False  False   False  False       False   False

[1000 rows x 7 columns]
       ID          Name   Age  Gender       City Occupation     Salary
0       1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1       2     Diya Khan   0.0    Male  Hyderabad          0   454230.0
2       3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3       4             0  36.0    Male          0   Engineer   363241.0
4       5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
..    ...           ...   ...     ...        ...        ...        ...
995   996  Vivaan Patel  18.0    Male    Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male     Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male     Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0       0    Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female     Jaipur     Doctor   916878.0

[1000 rows x 7 columns]

In [15]:
import pandas as pd
df=pd.read_csv("people1.csv")
print(df)
print(df.tail())
print(df.head())
print(df.shape)
print(df.columns)
print(df.index)
print(df.info())

       ID          Name   Age  Gender       City Occupation     Salary
0       1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1       2     Diya Khan   NaN    Male  Hyderabad        NaN   454230.0
2       3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3       4           NaN  36.0    Male        NaN   Engineer   363241.0
4       5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
..    ...           ...   ...     ...        ...        ...        ...
995   996  Vivaan Patel  18.0    Male    Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male     Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male     Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0     NaN    Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female     Jaipur     Doctor   916878.0

[1000 rows x 7 columns]
       ID          Name   Age  Gender     City Occupation     Salary
995   996  Vivaan Patel  18.0    Male  Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male   Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male   Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0     NaN  Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female   Jaipur     Doctor   916878.0
   ID          Name   Age  Gender       City Occupation     Salary
0   1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1   2     Diya Khan   NaN    Male  Hyderabad        NaN   454230.0
2   3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3   4           NaN  36.0    Male        NaN   Engineer   363241.0
4   5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
(1000, 7)
Index(['ID', 'Name', 'Age', 'Gender', 'City', 'Occupation', 'Salary'], dtype='str')
RangeIndex(start=0, stop=1000, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   Name        903 non-null    str
 2   Age         899 non-null    float64
 3   Gender      918 non-null    str
 4   City        918 non-null    str
 5   Occupation  918 non-null    str
 6   Salary      892 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 39.1 KB
None

In [16]:
print(df.shape)

(1000, 7)