In [2]:
import pandas as pd
print(pd.__version__)

3.0.2

In [5]:
#series
marks=pd.Series([80,70,20,77])
print(marks)

0    80
1    70
2    20
3    77
dtype: int64

In [6]:
fruits=pd.Series(["apple","mango","orange"])
print(fruits)

0     apple
1     mango
2    orange
dtype: str

In [7]:
marks = pd.Series([80,90,75],index=["A","B","C"]) 
print(marks)

A    80
B    90
C    75
dtype: int64

In [8]:
#data frame
students={"roll no.":[1,2,3,],"name":["sneha","sakshi","saloni"],"marks":[20,30,25]}
df=pd.DataFrame(students)
print(df)

   roll no.    name  marks
0         1   sneha     20
1         2  sakshi     30
2         3  saloni     25

In [9]:
print(df.tail())
print(df.head())
print(df.shape)
print(df.columns)
print(df.index)
print(df.info())
print(df.describe())

   roll no.    name  marks
0         1   sneha     20
1         2  sakshi     30
2         3  saloni     25
   roll no.    name  marks
0         1   sneha     20
1         2  sakshi     30
2         3  saloni     25
(3, 3)
Index(['roll no.', 'name', 'marks'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   roll no.  3 non-null      int64
 1   name      3 non-null      str
 2   marks     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 132.0 bytes
None
       roll no.  marks
count       3.0    3.0
mean        2.0   25.0
std         1.0    5.0
min         1.0   20.0
25%         1.5   22.5
50%         2.0   25.0
75%         2.5   27.5
max         3.0   30.0

In [11]:
print(df.head())
print(df.tail())
print(df.columns)
print(df.index)
print(df.info())
print(df.describe())
print(df.shape)

     ID     name department  salary
0  emp1   shreya         IT   12000
1  emp2  shivani         CS   13000
2  emp3    somya       AIML   14000
     ID     name department  salary
0  emp1   shreya         IT   12000
1  emp2  shivani         CS   13000
2  emp3    somya       AIML   14000
Index(['ID', 'name', 'department', 'salary'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          3 non-null      str
 1   name        3 non-null      str
 2   department  3 non-null      str
 3   salary      3 non-null      int64
dtypes: int64(1), str(3)
memory usage: 132.0 bytes
None
        salary
count      3.0
mean   13000.0
std     1000.0
min    12000.0
25%    12500.0
50%    13000.0
75%    13500.0
max    14000.0
(3, 4)

In [10]:
employee={"ID":["emp1","emp2","emp3"],"name":["shreya","shivani","somya"],"department":["IT","CS","AIML"],"salary":[12000,13000,14000]}
df=pd.DataFrame(employee)
print(df)

     ID     name department  salary
0  emp1   shreya         IT   12000
1  emp2  shivani         CS   13000
2  emp3    somya       AIML   14000

In [3]:
import pandas as pd
df=pd.read_csv("record.csv")
print(df)

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90

In [4]:
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.index) 
print(df.info())
print(df.describe())

           Name  English  Mathematics  Science  Social Studies  Computer
0  Aarav Sharma       85           92       78              88        95
1   Priya Verma       90           87       91              85        89
2   Rahul Singh       76           81       74              79        83
3  Ananya Gupta       95           93       96              90        98
4  Vikram Yadav       68           75       72              70        77
           Name  English  Mathematics  Science  Social Studies  Computer
5   Neha Mishra       88           84       89              92        86
6  Aditya Kumar       79           86       80              75        82
7   Sneha Patel       92           89       94              91        93
8   Rohan Mehta       73           78       85              80        76
9   Kavya Joshi       86           91       88              87        90
(10, 6)
Index(['Name', 'English', 'Mathematics', 'Science', 'Social Studies',
       'Computer'],
      dtype='str')
RangeIndex(start=0, stop=10, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            10 non-null     str
 1   English         10 non-null     int64
 2   Mathematics     10 non-null     int64
 3   Science         10 non-null     int64
 4   Social Studies  10 non-null     int64
 5   Computer        10 non-null     int64
dtypes: int64(5), str(1)
memory usage: 512.0 bytes
None
         English  Mathematics    Science  Social Studies   Computer
count  10.000000     10.00000  10.000000       10.000000  10.000000
mean   83.200000     85.60000  84.700000       83.700000  86.900000
std     8.829244      6.07728   8.340663        7.394442   7.430418
min    68.000000     75.00000  72.000000       70.000000  76.000000
25%    76.750000     81.75000  78.500000       79.250000  82.250000
50%    85.500000     86.50000  86.500000       86.000000  87.500000
75%    89.500000     90.50000  90.500000       89.500000  92.250000
max    95.000000     93.00000  96.000000       92.000000  98.000000

In [15]:
import pandas as pd
df=pd.read_csv("employes4.csv")
print(df)

   Employee ID\t      Name\t     Department\t          Salary
0   EMP001\t              Aarav Sharma\tHR\t      ...
1   EMP002\t               Priya Singh\tFinance   ...
2   EMP003\t               Rahul Verma\tIT\t      ...
3   EMP004\t               Sneha Gupta\tMarketing\...
4   EMP005\t               Arjun Mehta\tSales\t   ...
5   EMP006\t               Neha Kapoor\tIT\t      ...
6   EMP007\t               Karan Malhotra\tFinance...
7   EMP008\t               Ananya Joshi\tHR\t     ...
8   EMP009\t               Vivek Patel\tOperations...
9   EMP010\t               Isha Nair\tMarketing\t ...
10  EMP011\t               Rohan Das\tIT\t        ...
11  EMP012\t               Meera Reddy\tSales\t   ...
12  EMP013\t               Aditya Yadav\tOperation...
13  EMP014\t               Pooja Mishra\tHR\t     ...
14  EMP015\t               Saurabh Jain\tFinance\t...
15  EMP016\t               Kavya Iyer\tIT\t       ...
16  EMP017\t               Nitin Chawla\tSales\t  ...
17  EMP018\t               Riya Bansal\tMarketing\...
18  EMP019\t               Manish Kumar\tOperation...
19  EMP020\t               Simran Kaur\tFinance   ...

In [47]:
import pandas as pd
df=pd.read_csv("employee5.csv")
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())

In [43]:
import pandas as pd
df=pd.read_csv("employee5.csv")
df.fillna("not available")

    ID           Name Department         Salary
0    1          Aarav         HR        45000.0
1    2          Priya         IT        55000.0
2    3          Rahul    Finance        60000.0
3    4         Ananya  Marketing        50000.0
4    5         Vikram      Sales  not available
5    6           Neha         IT        65000.0
6    7          Rohan         HR        48000.0
7    8          Sneha    Finance        70000.0
8    9           Amit  Marketing  not available
9   10          Pooja      Sales        58000.0
10  11          Karan         IT        62000.0
11  12           Isha         HR        47000.0
12  13          Arjun    Finance        75000.0
13  14          Meera  Marketing        51000.0
14  15  not available      Sales        59000.0
15  16          Kavya         IT        68000.0
16  17         Suresh         HR        49000.0
17  18           Riya    Finance        72000.0
18  19         Manish  Marketing  not available
19  20          Tanya      Sales        56000.0

In [48]:
import pandas as pd
df=pd.read_csv("employee5.csv")
print(df.isnull())
print(df.isnull().sum())
df.fillna(5)
df.fillna(0)
df.fillna("not available")

       ID   Name  Department  Salary
0   False  False       False   False
1   False  False       False   False
2   False  False       False   False
3   False  False       False   False
4   False  False       False    True
5   False  False       False   False
6   False  False       False   False
7   False  False       False   False
8   False  False       False    True
9   False  False       False   False
10  False  False       False   False
11  False  False       False   False
12  False  False       False   False
13  False  False       False   False
14  False   True       False   False
15  False  False       False   False
16  False  False       False   False
17  False  False       False   False
18  False  False       False    True
19  False  False       False   False
ID            0
Name          1
Department    0
Salary        3
dtype: int64

In [23]:
df.groupby("Department")["Salary"].mean()

Department
Finance      69250.000000
HR           47250.000000
IT           62500.000000
Marketing    50500.000000
Sales        57666.666667
Name: Salary, dtype: float64

In [31]:
print(df.isnull())

       ID   Name  Department  Salary  Bonus
0   False  False       False   False  False
1   False  False       False   False  False
2   False  False       False   False  False
3   False  False       False   False  False
4   False  False       False    True  False
5   False  False       False   False  False
6   False  False       False   False  False
7   False  False       False   False  False
8   False  False       False    True  False
9   False  False       False   False  False
10  False  False       False   False  False
11  False  False       False   False  False
12  False  False       False   False  False
13  False  False       False   False  False
14  False   True       False   False  False
15  False  False       False   False  False
16  False  False       False   False  False
17  False  False       False   False  False
18  False  False       False    True  False
19  False  False       False   False  False

In [33]:
print(df.isnull().sum())

ID            0
Name          1
Department    0
Salary        3
Bonus         0
dtype: int64

In [34]:
df.dropna()

    ID    Name Department   Salary  Bonus
0    1   Aarav         HR  45000.0   5000
1    2   Priya         IT  55000.0   5000
2    3   Rahul    Finance  60000.0   5000
3    4  Ananya  Marketing  50000.0   5000
5    6    Neha         IT  65000.0   5000
6    7   Rohan         HR  48000.0   5000
7    8   Sneha    Finance  70000.0   5000
9   10   Pooja      Sales  58000.0   5000
10  11   Karan         IT  62000.0   5000
11  12    Isha         HR  47000.0   5000
12  13   Arjun    Finance  75000.0   5000
13  14   Meera  Marketing  51000.0   5000
15  16   Kavya         IT  68000.0   5000
16  17  Suresh         HR  49000.0   5000
17  18    Riya    Finance  72000.0   5000
19  20   Tanya      Sales  56000.0   5000

In [58]:
df.duplicated()
df.drop_duplicates()

    ID    Name Department   Salary
0    1   Aarav         HR  45000.0
1    2   Priya         IT  55000.0
2    3   Rahul    Finance  60000.0
3    4  Ananya  Marketing  50000.0
4    5  Vikram      Sales      NaN
5    6    Neha         IT  65000.0
6    7   Rohan         HR  48000.0
7    8   Sneha    Finance  70000.0
8    9    Amit  Marketing      NaN
9   10   Pooja      Sales  58000.0
10  11   Karan         IT  62000.0
11  12    Isha         HR  47000.0
12  13   Arjun    Finance  75000.0
13  14   Meera  Marketing  51000.0
14  15     NaN      Sales  59000.0
15  16   Kavya         IT  68000.0
16  17  Suresh         HR  49000.0
17  18    Riya    Finance  72000.0
18  19  Manish  Marketing      NaN
19  20   Tanya      Sales  56000.0

In [61]:
df.drop_duplicates()

    ID    Name Department   Salary
0    1   Aarav         HR  45000.0
1    2   Priya         IT  55000.0
2    3   Rahul    Finance  60000.0
3    4  Ananya  Marketing  50000.0
4    5  Vikram      Sales      NaN
5    6    Neha         IT  65000.0
6    7   Rohan         HR  48000.0
7    8   Sneha    Finance  70000.0
8    9    Amit  Marketing      NaN
9   10   Pooja      Sales  58000.0
10  11   Karan         IT  62000.0
11  12    Isha         HR  47000.0
12  13   Arjun    Finance  75000.0
13  14   Meera  Marketing  51000.0
14  15     NaN      Sales  59000.0
15  16   Kavya         IT  68000.0
16  17  Suresh         HR  49000.0
17  18    Riya    Finance  72000.0
18  19  Manish  Marketing      NaN
19  20   Tanya      Sales  56000.0

In [60]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [51]:
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
print(df)

    ID    Name Department        Salary
0    1   Aarav         HR  45000.000000
1    2   Priya         IT  55000.000000
2    3   Rahul    Finance  60000.000000
3    4  Ananya  Marketing  50000.000000
4    5  Vikram      Sales  58235.294118
5    6    Neha         IT  65000.000000
6    7   Rohan         HR  48000.000000
7    8   Sneha    Finance  70000.000000
8    9    Amit  Marketing  58235.294118
9   10   Pooja      Sales  58000.000000
10  11   Karan         IT  62000.000000
11  12    Isha         HR  47000.000000
12  13   Arjun    Finance  75000.000000
13  14   Meera  Marketing  51000.000000
14  15     NaN      Sales  59000.000000
15  16   Kavya         IT  68000.000000
16  17  Suresh         HR  49000.000000
17  18    Riya    Finance  72000.000000
18  19  Manish  Marketing  58235.294118
19  20   Tanya      Sales  56000.000000

In [52]:
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
print(df)

    ID    Name Department        Salary
0    1   Aarav         HR  45000.000000
1    2   Priya         IT  55000.000000
2    3   Rahul    Finance  60000.000000
3    4  Ananya  Marketing  50000.000000
4    5  Vikram      Sales  58235.294118
5    6    Neha         IT  65000.000000
6    7   Rohan         HR  48000.000000
7    8   Sneha    Finance  70000.000000
8    9    Amit  Marketing  58235.294118
9   10   Pooja      Sales  58000.000000
10  11   Karan         IT  62000.000000
11  12    Isha         HR  47000.000000
12  13   Arjun    Finance  75000.000000
13  14   Meera  Marketing  51000.000000
14  15     NaN      Sales  59000.000000
15  16   Kavya         IT  68000.000000
16  17  Suresh         HR  49000.000000
17  18    Riya    Finance  72000.000000
18  19  Manish  Marketing  58235.294118
19  20   Tanya      Sales  56000.000000

In [59]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [ ]:
df.dropna()
df.duplicated()
df.drop_duplicates()

import pandas as pd
df=pd.read_csv("people1.csv")
print(df)
print(df.tail())

In [6]:
import pandas as pd
df=pd.read_csv("people1.csv")
print(df.isnull())
print(df.fillna(0))

        ID   Name    Age  Gender   City  Occupation  Salary
0    False  False  False   False  False       False   False
1    False  False   True   False  False        True   False
2    False  False  False   False  False       False   False
3    False   True  False   False   True       False   False
4    False  False  False   False  False       False   False
..     ...    ...    ...     ...    ...         ...     ...
995  False  False  False   False  False       False   False
996  False  False  False   False  False       False   False
997  False  False  False   False  False       False   False
998  False  False  False    True  False       False   False
999  False  False  False   False  False       False   False

[1000 rows x 7 columns]
       ID          Name   Age  Gender       City Occupation     Salary
0       1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1       2     Diya Khan   0.0    Male  Hyderabad          0   454230.0
2       3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3       4             0  36.0    Male          0   Engineer   363241.0
4       5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
..    ...           ...   ...     ...        ...        ...        ...
995   996  Vivaan Patel  18.0    Male    Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male     Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male     Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0       0    Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female     Jaipur     Doctor   916878.0

[1000 rows x 7 columns]

In [4]:
import pandas as pd
df=pd.read_csv("people1.csv")
print(df)
print(df.tail())
print(df.head())
print(df.shape)
print(df.columns)
print(df.index)
print(df.info())

       ID          Name   Age  Gender       City Occupation     Salary
0       1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1       2     Diya Khan   NaN    Male  Hyderabad        NaN   454230.0
2       3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3       4           NaN  36.0    Male        NaN   Engineer   363241.0
4       5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
..    ...           ...   ...     ...        ...        ...        ...
995   996  Vivaan Patel  18.0    Male    Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male     Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male     Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0     NaN    Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female     Jaipur     Doctor   916878.0

[1000 rows x 7 columns]
       ID          Name   Age  Gender     City Occupation     Salary
995   996  Vivaan Patel  18.0    Male  Kolkata     Doctor  1209398.0
996   997  Ananya Patel  50.0    Male   Bhopal   Engineer   917162.0
997   998   Sneha Gupta  24.0    Male   Jaipur    Teacher   333093.0
998   999   Aarav Gupta  51.0     NaN  Lucknow   Engineer  1320299.0
999  1000  Rahul Sharma  58.0  Female   Jaipur     Doctor   916878.0
   ID          Name   Age  Gender       City Occupation     Salary
0   1  Aditya Verma  41.0    Male  Ahmedabad   Designer  1006465.0
1   2     Diya Khan   NaN    Male  Hyderabad        NaN   454230.0
2   3    Vivaan Das  34.0  Female    Lucknow     Doctor  1314173.0
3   4           NaN  36.0    Male        NaN   Engineer   363241.0
4   5  Aditya Verma  48.0    Male    Kolkata     Doctor   859777.0
(1000, 7)
Index(['ID', 'Name', 'Age', 'Gender', 'City', 'Occupation', 'Salary'], dtype='str')
RangeIndex(start=0, stop=1000, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   Name        903 non-null    str
 2   Age         899 non-null    float64
 3   Gender      918 non-null    str
 4   City        918 non-null    str
 5   Occupation  918 non-null    str
 6   Salary      892 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 39.1 KB
None

In [8]:
print(df.shape)

(1000, 7)

In [2]:
import pandas as pd
df=pd.read_csv("studends_laptop.csv")
print(df)

   | Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |
0   | ---------- | -------------- | ---------- | -...
1   | S001       | Aarav Sharma   | BCA        |  ...
2   | S002       | Ananya Singh   | B.Tech CSE |  ...
3   | S003       | Rohan Verma    | BCA        |  ...
4   | S004       | Priya Gupta    | B.Com      |  ...
5   | S005       | Vivek Yadav    | B.Tech IT  |  ...
6   | S006       | Neha Patel     | B.Sc       |  ...
7   | S007       | Arjun Mishra   | MCA        |  ...
8   | S008       | Sneha Roy      | MBA        |  ...
9   | S009       | Rahul Kumar    | BCA        |  ...
10  | S010       | Simran Kaur    | B.Tech AI  |  ...
11  | S011       | Karan Singh    | B.Tech CSE |  ...
12  | S012       | Aditi Sharma   | BCA        |  ...
13  | S013       | Mohit Jain     | B.Sc       |  ...
14  | S014       | Pooja Verma    | BBA        |  ...
15  | S015       | Aman Tiwari    | MCA        |  ...
16  | S016       | Isha Gupta     | B.Tech IT  |  ...
17  | S017       | Deepak Sharma  | BCA        |  ...
18  | S018       | Tanya Singh    | B.Tech ECE |  ...
19  | S019       | Nikhil Yadav   | B.Tech CSE |  ...
20  | S020       | Meera Kapoor   | MBA        |  ...
21  | S021       | Saurabh Gupta  | BCA        |  ...
22  | S022       | Ritika Sharma  | B.Sc       |  ...
23  | S023       | Akash Singh    | B.Tech AI  |  ...
24  | S024       | Divya Patel    | B.Com      |  ...
25  | S025       | Harsh Verma    | MCA        |  ...
26  | S026       | Komal Yadav    | BCA        |  ...
27  | S027       | Ayush Sharma   | B.Tech CSE |  ...
28  | S028       | Sakshi Gupta   | BBA        |  ...
29  | S029       | Rohit Kumar    | B.Sc       |  ...
30  | S030       | Nisha Singh    | B.Tech IT  |  ...
31  | S031       | Gaurav Mishra  | MCA        |  ...
32  | S032       | Riya Sharma    | BCA        |  ...
33  | S033       | Abhishek Yadav | B.Tech CSE |  ...
34  | S034       | Muskan Gupta   | MBA        |  ...
35  | S035       | Chirag Jain    | B.Sc       |  ...
36  | S036       | Palak Verma    | BCA        |  ...
37  | S037       | Aditya Singh   | B.Tech AI  |  ...
38  | S038       | Shreya Patel   | B.Com      |  ...
39  | S039       | Manish Kumar   | MCA        |  ...
40  | S040       | Khushi Roy     | BCA        |  ...
41  | S041       | Yash Sharma    | B.Tech IT  |  ...
42  | S042       | Tanvi Gupta    | B.Sc       |  ...
43  | S043       | Ritesh Singh   | MCA        |  ...
44  | S044       | Ayesha Khan    | MBA        |  ...
45  | S045       | Laksh Verma    | B.Tech CSE |  ...
46  | S046       | Kavya Mishra   | BCA        |  ...
47  | S047       | Siddharth Jain | B.Tech AI  |  ...
48  | S048       | Bhavna Sharma  | BBA        |  ...
49  | S049       | Rohan Patel    | B.Sc       |  ...
50  | S050       | Anjali Yadav   | MCA        |  ...

In [4]:
print(df.tail())
print(df.head())
print(df.columns)
print(df.shape)
print(df.index)
print(df.info())
print(df.describe())

   | Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |
46  | S046       | Kavya Mishra   | BCA        |  ...
47  | S047       | Siddharth Jain | B.Tech AI  |  ...
48  | S048       | Bhavna Sharma  | BBA        |  ...
49  | S049       | Rohan Patel    | B.Sc       |  ...
50  | S050       | Anjali Yadav   | MCA        |  ...
  | Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |
0  | ---------- | -------------- | ---------- | -...
1  | S001       | Aarav Sharma   | BCA        |  ...
2  | S002       | Ananya Singh   | B.Tech CSE |  ...
3  | S003       | Rohan Verma    | BCA        |  ...
4  | S004       | Priya Gupta    | B.Com      |  ...
Index(['| Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |'], dtype='str')
(51, 1)
RangeIndex(start=0, stop=51, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 1 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   | Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |  51 non-null     str
dtypes: str(1)
memory usage: 276.0 bytes
None
       | Student ID | Student Name   | Course     | Budget (₹) | Primary Use | Laptop Recommendation       |
count                                                  51
unique                                                 51
top     | ---------- | -------------- | ---------- | -...
freq                                                    1

In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df)

    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0         48        45        78        24         8        85         1
1         26        97        53        49        26         5        72
2         63        48        77        51        40        95        61
3          2        48        33        75        60        44        59
4         84        54       100        67        37        34        73
..       ...       ...       ...       ...       ...       ...       ...
95        62        53        81        90        38        65        67
96         5        94        23        33        19        60        24
97        15        40        84        10         9        47        27
98        25        73         9        16         4        33        55
99        36        79        49        14        22        12        27

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0         58        54         50         64         49         95         75
1         12        54         86         98         44         82         26
2        100        29         20         83         19         34         46
3         59        87         69         80         34         75         61
4         23        16         51         69         35          7         41
..       ...       ...        ...        ...        ...        ...        ...
95        62        54         54         32         17         91         63
96        73        58          5         36         17         83         78
97        15        96          7          3         37         96         64
98         3        20         88         37         74         49         13
99        57        92          6         51         88         28         32

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0          80         48         91          3         22         77
1          61         61         95         58         83         85
2          58         43         34          7         15         78
3          15         17         12         77          1         27
4          89         55         48         64         57         28
..        ...        ...        ...        ...        ...        ...
95        100         88         24          8         58         62
96         24         65         25         27         41         54
97         26         62         92         31          7         30
98         57         43         23         79         64         56
99         25         27         32         29         95         81

[100 rows x 20 columns]

In [3]:
print(df.shape)

(100, 20)

In [4]:
print(df.columns)
print(df.tail())
print(df.head())

Index(['Column_1', 'Column_2', 'Column_3', 'Column_4', 'Column_5', 'Column_6',
       'Column_7', 'Column_8', 'Column_9', 'Column_10', 'Column_11',
       'Column_12', 'Column_13', 'Column_14', 'Column_15', 'Column_16',
       'Column_17', 'Column_18', 'Column_19', 'Column_20'],
      dtype='str')
    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
95        62        53        81        90        38        65        67
96         5        94        23        33        19        60        24
97        15        40        84        10         9        47        27
98        25        73         9        16         4        33        55
99        36        79        49        14        22        12        27

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
95        62        54         54         32         17         91         63
96        73        58          5         36         17         83         78
97        15        96          7          3         37         96         64
98         3        20         88         37         74         49         13
99        57        92          6         51         88         28         32

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
95        100         88         24          8         58         62
96         24         65         25         27         41         54
97         26         62         92         31          7         30
98         57         43         23         79         64         56
99         25         27         32         29         95         81
   Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0        48        45        78        24         8        85         1
1        26        97        53        49        26         5        72
2        63        48        77        51        40        95        61
3         2        48        33        75        60        44        59
4        84        54       100        67        37        34        73

   Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0        58        54         50         64         49         95         75
1        12        54         86         98         44         82         26
2       100        29         20         83         19         34         46
3        59        87         69         80         34         75         61
4        23        16         51         69         35          7         41

   Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0         80         48         91          3         22         77
1         61         61         95         58         83         85
2         58         43         34          7         15         78
3         15         17         12         77          1         27
4         89         55         48         64         57         28

In [5]:
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Column_1   100 non-null    int64
 1   Column_2   100 non-null    int64
 2   Column_3   100 non-null    int64
 3   Column_4   100 non-null    int64
 4   Column_5   100 non-null    int64
 5   Column_6   100 non-null    int64
 6   Column_7   100 non-null    int64
 7   Column_8   100 non-null    int64
 8   Column_9   100 non-null    int64
 9   Column_10  100 non-null    int64
 10  Column_11  100 non-null    int64
 11  Column_12  100 non-null    int64
 12  Column_13  100 non-null    int64
 13  Column_14  100 non-null    int64
 14  Column_15  100 non-null    int64
 15  Column_16  100 non-null    int64
 16  Column_17  100 non-null    int64
 17  Column_18  100 non-null    int64
 18  Column_19  100 non-null    int64
 19  Column_20  100 non-null    int64
dtypes: int64(20)
memory usage: 15.7 KB
None
         Column_1    Column_2    Column_3    Column_4    Column_5    Column_6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
mean    47.450000   57.220000   51.450000   53.210000   50.760000   51.360000
std     28.306895   28.869466   29.609026   27.805346   30.591845   30.519581
min      2.000000    1.000000    1.000000    1.000000    3.000000    2.000000
25%     24.000000   34.750000   23.000000   29.750000   25.000000   22.750000
50%     44.000000   60.000000   49.500000   55.000000   46.000000   55.500000
75%     74.000000   82.250000   78.250000   78.000000   81.250000   77.500000
max     98.000000  100.000000  100.000000  100.000000   99.000000  100.000000

         Column_7    Column_8    Column_9   Column_10   Column_11  Column_12  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.00000
mean    55.220000   48.240000   46.160000   49.300000   48.810000   48.97000
std     29.336288   28.261449   31.373514   27.787978   28.921243   28.79059
min      1.000000    1.000000    4.000000    1.000000    3.000000    1.00000
25%     29.250000   23.750000   16.750000   28.000000   25.500000   24.75000
50%     59.000000   47.500000   41.000000   48.000000   47.000000   44.00000
75%     81.250000   67.750000   75.250000   71.000000   71.500000   75.25000
max     99.000000  100.000000  100.000000  100.000000  100.000000  100.00000

        Column_13   Column_14   Column_15   Column_16   Column_17   Column_18  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
mean    46.150000   47.140000   50.480000   51.040000   50.410000   55.630000
std     29.497261   30.875122   29.901684   26.263975   29.556347   27.750568
min      1.000000    1.000000    1.000000    2.000000    1.000000    2.000000
25%     20.000000   19.000000   25.000000   29.000000   24.000000   33.750000
50%     43.000000   45.500000   48.500000   51.000000   50.000000   55.000000
75%     70.500000   77.250000   80.000000   68.750000   78.500000   78.250000
max    100.000000   99.000000  100.000000  100.000000   98.000000  100.000000

        Column_19   Column_20
count  100.000000  100.000000
mean    53.010000   51.970000
std     28.108195   30.265977
min      1.000000    2.000000
25%     31.750000   25.000000
50%     54.500000   53.500000
75%     78.250000   79.000000
max    100.000000  100.000000

In [6]:
print(df.isnull())
print(df.fillna(0))
print(df.dropna())

    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0      False     False     False     False     False     False     False
1      False     False     False     False     False     False     False
2      False     False     False     False     False     False     False
3      False     False     False     False     False     False     False
4      False     False     False     False     False     False     False
..       ...       ...       ...       ...       ...       ...       ...
95     False     False     False     False     False     False     False
96     False     False     False     False     False     False     False
97     False     False     False     False     False     False     False
98     False     False     False     False     False     False     False
99     False     False     False     False     False     False     False

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0      False     False      False      False      False      False      False
1      False     False      False      False      False      False      False
2      False     False      False      False      False      False      False
3      False     False      False      False      False      False      False
4      False     False      False      False      False      False      False
..       ...       ...        ...        ...        ...        ...        ...
95     False     False      False      False      False      False      False
96     False     False      False      False      False      False      False
97     False     False      False      False      False      False      False
98     False     False      False      False      False      False      False
99     False     False      False      False      False      False      False

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0       False      False      False      False      False      False
1       False      False      False      False      False      False
2       False      False      False      False      False      False
3       False      False      False      False      False      False
4       False      False      False      False      False      False
..        ...        ...        ...        ...        ...        ...
95      False      False      False      False      False      False
96      False      False      False      False      False      False
97      False      False      False      False      False      False
98      False      False      False      False      False      False
99      False      False      False      False      False      False

[100 rows x 20 columns]
    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0         48        45        78        24         8        85         1
1         26        97        53        49        26         5        72
2         63        48        77        51        40        95        61
3          2        48        33        75        60        44        59
4         84        54       100        67        37        34        73
..       ...       ...       ...       ...       ...       ...       ...
95        62        53        81        90        38        65        67
96         5        94        23        33        19        60        24
97        15        40        84        10         9        47        27
98        25        73         9        16         4        33        55
99        36        79        49        14        22        12        27

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0         58        54         50         64         49         95         75
1         12        54         86         98         44         82         26
2        100        29         20         83         19         34         46
3         59        87         69         80         34         75         61
4         23        16         51         69         35          7         41
..       ...       ...        ...        ...        ...        ...        ...
95        62        54         54         32         17         91         63
96        73        58          5         36         17         83         78
97        15        96          7          3         37         96         64
98         3        20         88         37         74         49         13
99        57        92          6         51         88         28         32

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0          80         48         91          3         22         77
1          61         61         95         58         83         85
2          58         43         34          7         15         78
3          15         17         12         77          1         27
4          89         55         48         64         57         28
..        ...        ...        ...        ...        ...        ...
95        100         88         24          8         58         62
96         24         65         25         27         41         54
97         26         62         92         31          7         30
98         57         43         23         79         64         56
99         25         27         32         29         95         81

[100 rows x 20 columns]
    Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0         48        45        78        24         8        85         1
1         26        97        53        49        26         5        72
2         63        48        77        51        40        95        61
3          2        48        33        75        60        44        59
4         84        54       100        67        37        34        73
..       ...       ...       ...       ...       ...       ...       ...
95        62        53        81        90        38        65        67
96         5        94        23        33        19        60        24
97        15        40        84        10         9        47        27
98        25        73         9        16         4        33        55
99        36        79        49        14        22        12        27

    Column_8  Column_9  Column_10  Column_11  Column_12  Column_13  Column_14  \
0         58        54         50         64         49         95         75
1         12        54         86         98         44         82         26
2        100        29         20         83         19         34         46
3         59        87         69         80         34         75         61
4         23        16         51         69         35          7         41
..       ...       ...        ...        ...        ...        ...        ...
95        62        54         54         32         17         91         63
96        73        58          5         36         17         83         78
97        15        96          7          3         37         96         64
98         3        20         88         37         74         49         13
99        57        92          6         51         88         28         32

    Column_15  Column_16  Column_17  Column_18  Column_19  Column_20
0          80         48         91          3         22         77
1          61         61         95         58         83         85
2          58         43         34          7         15         78
3          15         17         12         77          1         27
4          89         55         48         64         57         28
..        ...        ...        ...        ...        ...        ...
95        100         88         24          8         58         62
96         24         65         25         27         41         54
97         26         62         92         31          7         30
98         57         43         23         79         64         56
99         25         27         32         29         95         81

[100 rows x 20 columns]